### ISSUE TITLE
Compute peakiness

### ISSUE THREAD

**Issue by jhidding** [abrupt-climate/notebooks#2]
It would be useful to analyse mostly events that show critical rate much faster than in other time periods (not only faster than in piC). => calculate the `peakiness' (for example peak-to-average ratio) of the global signal as an indicator, and report it in the output somehow. (this refers to the envelope of the signal plot, i.e.\ the maximum of the signal at each time; peak-to-average would mean the maximum of the signal at any time and place versus the time mean of the maximum at each point). I can then select the cases with largest peaks first for analysis.

**Comment by bathiany** [comment]
I will work on this first, in a notebook. Then we can implement this into hypercc and get one measure of peakiness as a number (global, or for each event) in the output.

**Comment by bathiany** [comment]
Update: All is ready.
See example notebook Peakiness.ipynb

Map with peakiness of all grid cells with edges: line 25.
Maximum value for this dataset: line 26

@jhidding : Please now implement lines 25 and 26 into hypercc.

Priority: high

**Comment by johan** [comment]
@bathiany You may want to refer to Johan by his github alias to notify the right person.

**Comment by bathiany** [comment]
@jhidding  very nice! One more thing: colour scales. 
1. Most of the peakiness map is now purple. please make white where there is no event.
2. the map called years: use the same colour bar as for peakiness (at the moment, colour bar ranges from light blue to dark blue which makes it very difficult to see when an event occurs).
After this, we can close this issue.
